stages = [
    "Premier League",
    "LaLiga",
    "Serie A",
    "Bundesliga",
    "Ligue 1",
    "Championship",
    "League One",
    "League Two",
    "Major League Soccer",
    "Eredivisie",
    "Liga Portugal",
    "Premiership",
    "Brasileirão",
    "Super Lig",
    "Premier League (RU)",
    "Jupiler Pro League",
    "2. Bundesliga",
]
