[project]
name = "pous"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.11.4",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
